language: go
go: 1.x
install:
- go get ./...
script:
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o tgbot_linux_64
- zip -r tgbot_linux_64.zip tgbot_linux_64 config
- CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o tgbot_linux_32
- zip -r tgbot_linux_32.zip tgbot_linux_32 config
- CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o tgbot_windows_64.exe
- zip -r tgbot_windows_64.zip tgbot_windows_64.exe config
- CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o tgbot_windows_32.exe
- zip -r tgbot_windows_32.zip tgbot_windows_32.exe config
deploy:
  provider: releases
  api_key:
    secure: BZy0B58PbjBxZpPEPxxt+JVV3x5MuM9Ca0q7uF3Z1PqWFEdoGgXQhWfHggEyd8EctEVCzr6MDFntAqsfFTG6mE9KJOlKOoUj4wkB1kTqUMNxWjR+5+8w8yAHHFwK9rQqgtpTtq3mL3euUox4UTzfliM2JWfGtkKJu0oKP2k6O0AbCV824506ZKe9cbTo0ato/DS8VizOcW7SXv3vupIjDW1EW5QziT7rReYjYf9o2quY0/muln80ennCHZn7uJxi4GS1rznN5R3iL1zfNXKzCUpwOTMTZbT2v6NLOHr1TCVINZofnnBMeQRoFt5GJcKRDZrlrSRENjFSd8q5p13TlB7pOOjwZnjwDXeqZ6famz41fZYtgxvXqgyie4iBrfXGSurCbdUW0vjgX3JOSMyG05PnZD+KUQUu3BKy77U38AK1E4Qbh1hmAfM2rv2qNJdpqlo7hvtb7QfUzXvlgXX0bzK7NyZp+MmZJ34wrHwe2KO/PuAvKivnBPGg9SLtZLr6wcyho+I1EvL+oDljEgcqMnxbiOlokJ0bN40YU4b9mSxNVGua41pDEFP5pyBsL9XYKMcAJJHnVKhQtNjLHagK+pn5/BtrVUt4HRM0OyID5s6YJFdTBhn1LG0TkiMeZda2t9OZwDoTBFQjwEcC2F99nxRcba4olBj/8kc6Q8wmTF0=
  file:
    - *.zip
  skip_cleanup: true
  on:
    repo: coolrc136/go-tg-bot
    tags: true
